Documents/projetos/project_barber_shop/barbershop/barber_shop/Models/ViewModel/HomeViewModel.cs
namespace barber_shop.Models.ViewModel
{
    public class HomeViewModel
    {
        public Service[] Services { get; set; }
        public User[] Barbers { get; set; }
    }
}

Documents/projetos/project_barber_shop/barbershop/barber_shop/Controllers/DashboardController.cs
using barber_shop.Commands;
using barber_shop.Extensions;
using barber_shop.Models;
using barber_shop.Models.Enums;
using barber_shop.Models.ViewModel;
using barber_shop.Services;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;

namespace barber_shop.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IBarberShopRepository _barberShopRepository;
        private readonly IUpdatePassword _updatePassword;
        private readonly IEditAccountDetails _editAccountDetails;
        private readonly IInsertPhotoOfBarberServices _insertPhotoOfBarberServices;

        public DashboardController(
            IBarberShopRepository barberShopRepository,
            IUpdatePassword updatePassword,
            IEditAccountDetails editAccountDetails,
            IInsertPhotoOfBarberServices insertPhotoOfBarberServices)
        {
            _barberShopRepository = barberShopRepository;
            _updatePassword = updatePassword;
            _editAccountDetails = editAccountDetails;
            _insertPhotoOfBarberServices = insertPhotoOfBarberServices;
        }

        public async Task<IActionResult> MyDashboard()
        {
            Scheduling[] mySchedluings;
            var user = await _barberShopRepository.GetUserLoggedInByCpf(User.Identity.Name);
            if (User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR))
            {
                return RedirectToAction("Index", "Administrator");
            }

            if (User.Claims.First().Value == nameof(EnumAccountCategory.BARBER))
            {
                mySchedluings = await _barberShopRepository.GetBarberSchedules(user.Id);
            }
            else
            {
                mySchedluings = await _barberShopRepository.GetUserSchedules(user.Id);
            }
            var viewModel = new DashboardViewModel
            {
                Schedulings = mySchedluings,
                User = user
            };
            return View(viewModel);
        }

        public async Task<IActionResult> ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(User obj)
        {
            try
            {
                await _updatePassword.Excute(obj, User.Identity.Name);
                return RedirectToAction(nameof(MyDashboard));
            }
            catch (Exception ex)
            {
                TempData["ErrorChange"] = ex.Message;
                return View();
            }
        }

        public async Task<IActionResult> EditAccountDetails(int id)
        {
            var genders = await _barberShopRepository.GetGenders();
            var user = await _barberShopRepository.GetUserById(id);
            var viewModel = new UserFormViewModel { User = user, Genders = genders };
            if (User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR))
            {
                viewModel.AccountCategories = await _barberShopRepository.GetAccountCategories();
            }

            if (user.Cpf != User.Identity.Name)
            {
                if (!(User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR)))
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAccountDetails(UserFormViewModel obj, IFormFile Image)
        {
            if (Image is not null)
            {
                MemoryStream target = new MemoryStream();
                Image.CopyToAsync(target);
                byte[] img = target.ToArray();
                obj.User.Profile.Image = img;
            }
            try
            {
                await _editAccountDetails.Execute(obj, User.Identity.Name, User.Claims.First().Value.ToString());
                if (User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR))
                {
                    return RedirectToAction("Index", "Administrator");
                }
                return RedirectToAction(nameof(MyDashboard));
            }
            catch (Exception ex)
            {
                TempData["ErrorEditAccount"] = ex.Message;
                var genders = await _barberShopRepository.GetGenders();
                var user = await _barberShopRepository.GetUserById(obj.User.Id);
                var viewModel = new UserFormViewModel { User = user, Genders = genders };
                if (User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR))
                {
                    viewModel.AccountCategories = await _barberShopRepository.GetAccountCategories();
                }
                return View(viewModel);
            }
        }

        public async Task<IActionResult> DashboardBarber(int id)
        {
            var barber = await _barberShopRepository.GetUserById(id);
            var commentsBarber = await _barberShopRepository.GetBarberCommentById(barber.Id);
            var photosOfBarberServices = await _barberShopRepository.GetPhotosOfTheBarberServicesById(barber.Id);
            var viewModel = new DashboardBarberViewModel
            {
                Barber = barber,
                Assessments = commentsBarber,
                PhotoOfBarberServices = photosOfBarberServices
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(EnumAccountCategory.CLIENT))]
        public async Task<IActionResult> EvaluatesBarber(string comments, int idBarber, string cpf)
        {
            try
            {
                var user = await _barberShopRepository.GetUserByCpf(cpf);
                var assesments = new Assessments
                {
                    BarberId = idBarber,
                    ClientId = user.Id,
                    Description = comments,
                };
                await _barberShopRepository.Insert(assesments);
            }
            catch (Exception ex)
            {
                TempData["ErroUpdateScheduling"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> AddMyPhotoToMyGallery()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(EnumAccountCategory.BARBER))]
        public async Task<IActionResult> AddMyPhotoToMyGallery(
            string cpf,
            IFormFile Image)
        {
            try
            {
                await _insertPhotoOfBarberServices.Execute(cpf, Image);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return View();
            }
            return RedirectToAction(nameof(MyDashboard));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(EnumAccountCategory.BARBER))]
        public async Task<IActionResult> DeletePhotoToMyGallery(int id)
        {
            var photoGallery = await _barberShopRepository.GetPhotoOfTheBarberGalleryById(id);
            await _barberShopRepository.Delete(photoGallery);
            return RedirectToAction(nameof(MyDashboard));
        }
    }
}

Documents/projetos/project_barber_shop/barbershop/barber_shop/Controllers/HomeController.cs
using barber_shop.Models;
using barber_shop.Models.ViewModel;
using barber_shop.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Security.Claims;

namespace barber_shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBarberShopRepository _barberShopRepository;

        public HomeController(ILogger<HomeController> logger, IBarberShopRepository barberShopRepository)
        {
            _logger = logger;
            _barberShopRepository = barberShopRepository;
        }

        public async Task<IActionResult> Index()
        {
            var services = await _barberShopRepository.GetServices();
            var barbers = await _barberShopRepository.GetAllBarbers();
            var viewModel = new HomeViewModel { Services = services, Barbers = barbers };
            return View(viewModel);
        }
    }
}

Documents/projetos/project_barber_shop/barbershop/barber_shop/Controllers/ServiceController.cs
using barber_shop.Commands;
using barber_shop.Models;
using barber_shop.Models.Enums;
using barber_shop.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace barber_shop.Controllers
{
    [Authorize(Roles = nameof(EnumAccountCategory.ADMINISTRATOR))]
    public class ServiceController : Controller
    {
        private readonly IInsertService _insertService;
        private readonly IBarberShopRepository _barberShopRepository;
        private readonly IUpdateService _updateService;
        private readonly IDeleteService _deleteService;

        public ServiceController(
            IInsertService insertService,
            IBarberShopRepository barberShopRepository,
            IUpdateService updateService,
            IDeleteService deleteService
            )
        {
            _insertService = insertService;
            _barberShopRepository = barberShopRepository;
            _updateService = updateService;
            _deleteService = deleteService;
        }

        public async Task<IActionResult> Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(Service obj, IFormFile Image)
        {
            try
            {
                if (Image == null)
                {
                    throw new Exception("A imagem precisa ser inserida.");
                }
                MemoryStream target = new MemoryStream();
                Image.CopyToAsync(target);
                byte[] img = target.ToArray();
                obj.Image = img;
                await _insertService.Execute(obj);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                TempData["ErrorRegister"] = ex.Message;
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var service = await _barberShopRepository.GetService(id);
            return View(service);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Service obj, IFormFile Image)
        {
            try
            {
                if (Image == null)
                {
                    throw new Exception("A imagem precisa ser inserida.");
                }
                MemoryStream target = new MemoryStream();
                Image.CopyToAsync(target);
                byte[] img = target.ToArray();
                obj.Image = img;
                await _updateService.Execute(obj);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                TempData["ErrorRegister"] = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _deleteService.Execute(id);
                TempData["SuccessDelete"] = "Servico Deletado";
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                TempData["ErrorDelete"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Documents/projetos/project_barber_shop/barbershop/barber_shop/Views/Home/Index.cshtml
<link rel="stylesheet" type="text/css" href="~/css/service/card.css" />
<link rel="stylesheet" type="text/css" href="~/css/home.css" />
<link rel="stylesheet" type="text/css" href="~/css/home/index.css" />
@using barber_shop.Models.Enums;
@model barber_shop.Models.ViewModel.HomeViewModel;
@{
    ViewData["Title"] = "Home";
}

@if (TempData["ErroUpdateScheduling"] is not null)
{
    <script>
        Swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: '@TempData["ErroUpdateScheduling"].ToString()'
        })
    </script>
}

@if (TempData["ErrorDelete"] is not null)
{
    <script>
        Swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: 'Não é possível deletar o serviço pois o mesmo tem agendamento'
        })
    </script>
}
else if (TempData["SuccessDelete"] is not null)
{
    <script>
        Swal.fire({
            icon: 'success',
            title: 'Serviço deletado!',
            showConfirmButton: false,
            timer: 2000
        })
    </script>
}

<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="5000">
            <img src="imgs/pexels-nikolaos-dimou-1319460 (1).jpg" class="d-block w-100" alt="img1carousel">
        </div>
        <div class="carousel-item" data-bs-interval="5000">
            <img src="imgs/pexels-dmitry-zvolskiy-1570807 (1).jpg" class="d-block w-100" alt="img2carousel">
        </div>
        <div class="carousel-item" data-bs-interval="5000">
            <img src="imgs/pexels-dmitry-zvolskiy-1570806 (1).jpg" class="d-block w-100" alt="img3carousel">
        </div>
    </div>
</div>

<hr />

<div class="text-center">
    <h1 class="display-4">Bem Vindo Usuário</h1>
</div>

<hr />
<br />
<br />
<div class="qmsomos">
    <div class="containerqmsomos">
        <div class="boxqmsomos">
            <span class="titleqmsomos"><br />Quem somos?<hr /></span>
            <div class="divqmsomos">
                <p>
                    &nbsp Somos a BarberShop, o seu destino definitivo para cuidados masculinos de alta qualidade. Nossa equipe de profissionais experientes é apaixonada por realçar a sua beleza e confiança. Oferecemos uma variedade de serviços, incluindo cortes de cabelo, barbas precisas, combos de corte + barba, luzes para um toque de estilo e cuidados especializados com sobrancelhas. Na BarberShop, seu visual é nossa prioridade, e estamos comprometidos em oferecer um serviço excepcional a cada visita.

                    Venha experimentar o que faz da BarberShop a escolha preferida de homens que valorizam a qualidade e o estilo. Seu próximo look está a apenas uma visita de distância.<br />
                </p>

            </div>
            <hr />
            <b class="bqmsomos">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp BarberShop - Estilo e Confiabilidade</b>
        </div>
    </div>

    <div class="center-screen">
        <div class="imgqmsomos">
            <img src="~/imgs/pexels-caleb-oquendo-3162022 (3).jpg" />
        </div>
    </div>
</div>

<br />
<br />

<hr />

<div class="text-center">
    <h1 class="display-4" id="serv">Serviços</h1><!--ID SERV para tela ir até serviços-->
    <hr />
    @if (User.Identity.IsAuthenticated)
    {
        if (User.Claims.First().Value == EnumAccountCategory.ADMINISTRATOR.ToString())
        {
            <a asp-action="Register" asp-controller="Service" class="btn btn-primary" id="btn-nenhum-cadastro">Create New</a>
        }
    }
</div>

@foreach (var item in Model.Services)
{
    <div class="card" style="display: inline-block;  margin: 99px; justify-content:center">
        <div class="card-img">
            @{
                var base64 = Convert.ToBase64String(item.Image);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            }
            <img src="@imgSrc" alt="img-service" style="max-width:200px; max-height:200px;">
        </div>
        <div class="card-title">@item.Name</div>
        <div class="card-subtitle"></div>
        <div class="card-footer">
            <div class="card-price"><span>R$</span>@item.Value</div>
            &nbsp;
            <button class="card-btn">
                <a asp-action="ToSchedule" asp-controller="Scheduling" class="agendar">Agendar</a>
            </button>

        </div>

        @if (User.Identity.IsAuthenticated)
        {
            if (User.Claims.First().Value == EnumAccountCategory.ADMINISTRATOR.ToString())
            {
                <div class="btnadm">
                    <a asp-action="Edit" asp-controller="Service" asp-route-id="@item.Id" class="btn btn-primary">Editar</a>
                    <form asp-action="Delete" id="type" asp-controller="Service" method="post" asp-route-id="@item.Id" onsubmit="return Confirmar()">
                        <button id="btn-deletar" type="submit" class="btn btn-danger">Deletar</button>
                    </form>
                </div>
            }
        }
    </div>
}

<br />
<hr />
<div class="text-center">
    <h1 class="display-4" id="serv">Barbeiros</h1>
    <hr />
</div>

@foreach (var item in Model.Barbers)
{
    <div class="container-barber" style="display: inline-block;  margin: 94px; justify-content:center">
        <div class="card-barber">
            <div class="front">
                <div class="card-top">
                    <p class="card-top-para">Barbeiro</p>
                </div>
                <br>

                <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
                </svg>
                <p class="heading">
                    @{
                        string result;
                        var nameFormat = item.Name.Split(' ');
                        if (nameFormat.Length >= 2)
                        {
                            result = $"{nameFormat[0]} {nameFormat[1]}";
                        }
                        else
                        {
                            result = item.Name;
                        }
                    }
                    @result
                </p>
                <p class="follow">
                    Conheça-me mais...
                </p>
            </div>
            <div class="back">
                <p class="heading">Meu Perfil</p>

                <p class="follow">
                    Clique no ícone
                </p>

                <div class="icons">
                    <a asp-action="DashboardBarber" asp-controller="Dashboard" asp-route-id="@item.Id" style="text-decoration: none; color: currentColor;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/js/alert.js"></script>