Documents/projetos/project_barber_shop/barbershop/barber_shop/Controllers/DashboardController.cs
using barber_shop.Commands;
using barber_shop.Extensions;
using barber_shop.Models;
using barber_shop.Models.Enums;
using barber_shop.Models.ViewModel;
using barber_shop.Services;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;

namespace barber_shop.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IBarberShopRepository _barberShopRepository;
        private readonly IUpdatePassword _updatePassword;
        private readonly IEditAccountDetails _editAccountDetails;
        private readonly IInsertPhotoOfBarberServices _insertPhotoOfBarberServices;

        public DashboardController(
            IBarberShopRepository barberShopRepository,
            IUpdatePassword updatePassword,
            IEditAccountDetails editAccountDetails,
            IInsertPhotoOfBarberServices insertPhotoOfBarberServices)
        {
            _barberShopRepository = barberShopRepository;
            _updatePassword = updatePassword;
            _editAccountDetails = editAccountDetails;
            _insertPhotoOfBarberServices = insertPhotoOfBarberServices;
        }

        public async Task<IActionResult> MyDashboard()
        {
            Scheduling[] mySchedluings;
            var user = await _barberShopRepository.GetUserLoggedInByCpf(User.Identity.Name);
            if (User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR))
            {
                return RedirectToAction("Index", "Administrator");
            }

            if (User.Claims.First().Value == nameof(EnumAccountCategory.BARBER))
            {
                mySchedluings = await _barberShopRepository.GetBarberSchedules(user.Id);
            }
            else
            {
                mySchedluings = await _barberShopRepository.GetUserSchedules(user.Id);
            }
            var viewModel = new DashboardViewModel
            {
                Schedulings = mySchedluings,
                User = user
            };
            return View(viewModel);
        }

        public async Task<IActionResult> ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(User obj)
        {
            try
            {
                await _updatePassword.Excute(obj, User.Identity.Name);
                return RedirectToAction(nameof(MyDashboard));
            }
            catch (Exception ex)
            {
                TempData["ErrorChange"] = ex.Message;
                return View();
            }
        }

        public async Task<IActionResult> EditAccountDetails(int id)
        {
            var genders = await _barberShopRepository.GetGenders();
            var user = await _barberShopRepository.GetUserById(id);
            var viewModel = new UserFormViewModel { User = user, Genders = genders };
            if (User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR))
            {
                viewModel.AccountCategories = await _barberShopRepository.GetAccountCategories();
            }

            if (user.Cpf != User.Identity.Name)
            {
                if (!(User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR)))
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAccountDetails(UserFormViewModel obj, IFormFile Image)
        {
            if (Image is not null)
            {
                MemoryStream target = new MemoryStream();
                Image.CopyToAsync(target);
                byte[] img = target.ToArray();
                obj.User.Profile.Image = img;
            }
            try
            {
                await _editAccountDetails.Execute(obj, User.Identity.Name, User.Claims.First().Value.ToString());
                if (User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR))
                {
                    return RedirectToAction("Index", "Administrator");
                }
                return RedirectToAction(nameof(MyDashboard));
            }
            catch (Exception ex)
            {
                TempData["ErrorEditAccount"] = ex.Message;
                var genders = await _barberShopRepository.GetGenders();
                var user = await _barberShopRepository.GetUserById(obj.User.Id);
                var viewModel = new UserFormViewModel { User = user, Genders = genders };
                if (User.Claims.First().Value == nameof(EnumAccountCategory.ADMINISTRATOR))
                {
                    viewModel.AccountCategories = await _barberShopRepository.GetAccountCategories();
                }
                return View(viewModel);
            }
        }

        public async Task<IActionResult> DashboardBarber(int id)
        {
            var barber = await _barberShopRepository.GetUserById(id);
            var commentsBarber = await _barberShopRepository.GetBarberCommentById(barber.Id);
            var photosOfBarberServices = await _barberShopRepository.GetPhotosOfTheBarberServicesById(barber.Id);
            var viewModel = new DashboardBarberViewModel
            {
                Barber = barber,
                Assessments = commentsBarber,
                PhotoOfBarberServices = photosOfBarberServices
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(EnumAccountCategory.CLIENT))]
        public async Task<IActionResult> EvaluatesBarber(string comments, int idBarber, string cpf)
        {
            try
            {
                var user = await _barberShopRepository.GetUserByCpf(cpf);
                var assesments = new Assessments
                {
                    BarberId = idBarber,
                    ClientId = user.Id,
                    Description = comments,
                };
                await _barberShopRepository.Insert(assesments);
            }
            catch (Exception ex)
            {
                TempData["ErroUpdateScheduling"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> AddMyPhotoToMyGallery()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(EnumAccountCategory.BARBER))]
        public async Task<IActionResult> AddMyPhotoToMyGallery(
            string cpf,
            IFormFile Image)
        {
            try
            {
                await _insertPhotoOfBarberServices.Execute(cpf, Image);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return View();
            }
            return RedirectToAction(nameof(MyDashboard));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(EnumAccountCategory.BARBER))]
        public async Task<IActionResult> DeletePhotoToMyGallery(int id)
        {
            var photoGallery = await _barberShopRepository.GetPhotoOfTheBarberGalleryById(id);
            await _barberShopRepository.Delete(photoGallery);
            return RedirectToAction(nameof(MyDashboard));
        }
    }
}

Documents/projetos/project_barber_shop/barbershop/barber_shop/Controllers/SchedulingController.cs
using barber_shop.Commands;
using barber_shop.Models;
using barber_shop.Models.Enums;
using barber_shop.Models.ViewModel;
using barber_shop.Services;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace barber_shop.Controllers
{
    [Authorize]
    public class SchedulingController : Controller
    {
        private readonly IBarberShopRepository _barberShopRepository;
        private readonly IInsertScheduling _insertScheduling;
        private readonly IGenerateReport _generateReport;
        private readonly IUpdateScheduling _updateScheduling;
        private readonly IDeleteScheduling _deleteScheduling;

        public SchedulingController(
            IBarberShopRepository barberShopRepository,
            IInsertScheduling insertScheduling,
            IGenerateReport generateReport,
            IUpdateScheduling updateScheduling,
            IDeleteScheduling deleteScheduling
            )
        {
            _barberShopRepository = barberShopRepository;
            _insertScheduling = insertScheduling;
            _generateReport = generateReport;
            _updateScheduling = updateScheduling;
            _deleteScheduling = deleteScheduling;
        }

        [Authorize(Roles = nameof(EnumAccountCategory.ADMINISTRATOR))]
        public async Task<IActionResult> Index(int? id)
        {
            Scheduling[] schedulings;
            if (id is not null)
            {
                schedulings = await _barberShopRepository.GetUserSchedules(id.Value);
            }
            else
            {
                schedulings = await _barberShopRepository.GetAllSchedulings();
            }
            return View(schedulings);
        }

        public async Task<IActionResult> ToSchedule()
        {
            var schedulingTimes = await _barberShopRepository.GetAllSchedulingTimes();
            var barbers = await _barberShopRepository.GetAllBarbers();
            var services = await _barberShopRepository.GetServices();
            SchedulingFormViewModel viewModel = new SchedulingFormViewModel { Services = services, Barbers = barbers, SchedulingTimes = schedulingTimes };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ToSchedule(SchedulingFormViewModel obj)
        {
            try
            {
                await _insertScheduling.Execute(obj, User.Identity.Name);
                //retorna algum redirect (página dizendo que foi agendado)
                return RedirectToAction(nameof(Index), "Home");
            }
            catch (Exception ex)
            {
                TempData["ErrorScheduling"] = ex.Message;
                var schedulingTimes = await _barberShopRepository.GetAllSchedulingTimes();
                var barbers = await _barberShopRepository.GetAllBarbers();
                var services = await _barberShopRepository.GetServices();
                SchedulingFormViewModel viewModel = new SchedulingFormViewModel { Services = services, Barbers = barbers, SchedulingTimes = schedulingTimes };
                return View(viewModel);
            }
        }

        public async Task<IActionResult> ReSchedule(int id)
        {
            var schedulingById = await _barberShopRepository.GetSchedulingById(id);
            if (DateOnly.FromDateTime(schedulingById.Date) < DateOnly.FromDateTime(DateTime.Now))
            {
                TempData["ErroUpdateScheduling"] = "Nao e possivel reagendar este agendamento.";
                return RedirectToAction("Index", "Home");
            }
            var schedulingTimes = await _barberShopRepository.GetAllSchedulingTimes();
            var barbers = await _barberShopRepository.GetAllBarbers();
            var services = await _barberShopRepository.GetServices();
            var viewModel = new SchedulingFormViewModel { Services = services, Barbers = barbers, SchedulingTimes = schedulingTimes, Scheduling = schedulingById };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReSchedule(SchedulingFormViewModel obj)
        {
            try
            {
                await _updateScheduling.Execute(obj, User.Identity.Name);
                if (User.Claims.First().Value == EnumAccountCategory.ADMINISTRATOR.ToString())
                {
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction("MyDashboard", "Dashboard");
            }
            catch (Exception ex)
            {
                var schedulingById = await _barberShopRepository.GetSchedulingById(obj.Scheduling.Id);
                var schedulingTimes = await _barberShopRepository.GetAllSchedulingTimes();
                var barbers = await _barberShopRepository.GetAllBarbers();
                var services = await _barberShopRepository.GetServices();
                var viewModel = new SchedulingFormViewModel { Services = services, Barbers = barbers, SchedulingTimes = schedulingTimes, Scheduling = schedulingById };
                TempData["ErroUpdateScheduling"] = ex.Message;
                return View(viewModel);
            }
        }

        [HttpPost]
        [Authorize(Roles = nameof(EnumAccountCategory.ADMINISTRATOR))]
        public async Task<ActionResult<Scheduling[]>> GenerateReport(
          DateTimeOffset mindate,
          DateTimeOffset maxdate
        )
        {
            try
            {
                await _generateReport.Execute(mindate, maxdate, User.Identity.Name);
                TempData["GeneratedReport"] = "Relatorio gerado e enviado";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex )
            {
                TempData["ErrorGeneratedReport"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteScheduling(int id)
        {
            try
            {
                await _deleteScheduling.Exectute(id);
                if (User.Claims.First().Value == EnumAccountCategory.ADMINISTRATOR.ToString())
                {
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction("MyDashboard", "Dashboard");
            }
            catch (Exception ex)
            {
                TempData["DeleteScheduling"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(EnumAccountCategory.ADMINISTRATOR))]
        public async Task<IActionResult> CompleteAppointments()
        {
            await _barberShopRepository.CompleteAppointments();
            return RedirectToAction(nameof(Index));
        }
    }
}

Documents/projetos/project_barber_shop/barbershop/barber_shop/Views/Shared/_Layout.cshtml
@using barber_shop.Models.Enums;
@using Microsoft.AspNetCore.Identity;
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - BarberShop</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/barbearia.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/barber_shop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/css/footer.css" />
    <link rel="stylesheet" type="text/css" href="~/css/formLogin.css" />
    <link rel="stylesheet" type="text/css" href="~/css/formRegister.css" />
    <link rel="stylesheet" type="text/css" href="~/css/service/scheduling.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BarberShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">BarberShop</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/#serv">Serviços</a>

                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-controller="Scheduling" asp-action="ToSchedule">Agendamento</a>
                            </li>
                            <!--Colocar dashbord do cliente para ter informações a conta dele-->
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="btn btn-outline-secondary mt-4" asp-action="MyDashboard" asp-controller="Dashboard">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                                        </svg>
                                    </a>
                                    <a class="text-dark btn btn-danger mt-4" asp-area="" asp-controller="Access" asp-action="LogOut" style="display: inline-block;">Sair</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" asp-controller="Access" asp-action="Login">Entrar</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
    <footer>
    <div class="footer-content">
        &copy;BarberShop - Av. Imperatriz Leopoldina, até 550 - lado par, São Paulo - SP, 05305-000
    </div>
    </footer>
</html>